version: "3.9"
services:
    db:
        image: mysql:8.0
        restart: always
        platform: linux/amd64 # enable compatibility for M1 Macs
        environment:
            MYSQL_DATABASE: customers
            MYSQL_USER: test_user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: {}